package:
  name: gedidb
  version: 2.0.0

source:
  url: https://pypi.io/packages/source/g/gedidb/gedidb-2.0.0.tar.gz
  sha256: <INSERT_SHA256_HASH>

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.12
    - pip
  run:
    - python >=3.12
    - pandas ==2.2.2
    - geopandas ==1.0.1
    - pyarrow ==17.0.0
    - h5py ==3.11.0
    - numpy ==2.0.1
    - dask-jobqueue ==0.9.0
    - xarray ==2024.7.0
    - Cartopy ==0.23.0
    - retry ==0.9.2
    - dask ==2024.8.2
    - distributed ==2024.8.2
    - bokeh ==3.6.0
    - boto3 ==1.35.49
    - tiledb ==0.33.2
    - scipy ==1.14.1

  test:
    imports:
      - gedidb
    requires:
      - pytest

about:
  home: https://git.gfz-potsdam.de/global-land-monitoring/gedi-toolbox
  license: EUPL-1.2
  license_family: EUPL
  summary: >-
    A toolbox to download, process, store and visualize Global Ecosystem Dynamics
    Investigation (GEDI) L2A-B and L4A-C data.
  description: >-
    gedidb is a Python-based toolbox for managing Global Ecosystem Dynamics Investigation
    (GEDI) data. It allows for downloading, processing, storing, and visualizing GEDI L2A-B
    and L4A-C data efficiently, supporting workflows in geospatial data science.

extra:
  recipe-maintainers:
    - besnard@gfz-potsdam.de
    - felix.dombrowski@uni-potsdam.de
    - amelia.holcomb@gmail.com

