name: gedidb

channels: &id1
  - conda-forge

dependencies:
  - python=3.12.*
  - pip<=24.0
  # setup requirements
  - tox
  # test requirements
  - pytest
  - pytest-cov
  - urlchecker
  - mypy
  # lint requirements
  - flake8
  - pycodestyle
  - pydocstyle
  # doc requirements
  - sphinx>=4.1.1
  - sphinx-argparse
  # - sphinx_autodoc_typehints
  - sphinx_rtd_theme
  - numpydoc>=1.7
  # deployment requirements
  - twine
 # code requirements
  - boto3
  - dask
  - distributed
  - geopandas
  - h5py
  - numpy
  - pandas
  - requests
  - retry
  - scipy
  - tiledb
  - xarray
    
  - pip:
          - pytest-reporter-html1
