name: Draft PDF

on: [push]

permissions:
  contents: write

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md

      - name: Upload draft PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper/paper.pdf